### ISSUE TITLE
Passing configuration parameters to ZAP before scan starts

### ISSUE THREAD

**Issue by Shukherberg** [carrier-io/carrier-io#31]
Hi,
In desktop appliance of OWASP ZAP there are options to change Active scan's properties such as number of hosts scanned concurrently, number of threads scanning per host and also option to exclude particular URLs from scan. These options can be configured manually in graphic interface or via API calls to zap server. Is it possible to somehow pass these configurations in carries dast 2.0, before scan starts?

**Comment by arozumenko** [comment]
Yes, you can export your scan profile and pass it to DAST. 
@LifeDJIK Please assist on how-tos

**Comment by LifeDJIK** [comment]
Hi @Shukherberg,

Here is how you can add excludes:
```
zap:
  <...other options here...>
  exclude: # (optional) URLs regex to exclude from scan
  - http://app:8080/logout.*
  exclude_from_context: true # (optional) True/False to add data from exclude option. Or URLs regex list to exclude from context
  exclude_from_spider: true # (optional) True/False to add data from exclude option. Or URLs regex list to exclude from spider
  exclude_from_ascan: true # (optional) True/False to add data from exclude option. Or URLs regex list to exclude from active scan
  exclude_from_proxy: true # (optional) True/False to add data from exclude option. Or URLs regex list to exclude from proxy
```

Also you can supply context file exported from ZAP:
```
zap:
  <...>
  context_file: /path/to/zap_context
```

If you need additional command line options for ZAP daemon - they can be set too:
```
zap:
  <...>
  java_options: -Xmx2g
```

_Note_: Carrier DAST/SAST 2.0 supports sample config generation. Just run:
```
docker run --rm getcarrier/dast:2.0 generate-config
```

We may add other options in future (those ones that can be configured via API).

_Another note_: Carrier "latest" DAST image additionally supports loading pre-configured scan policy from file:
```
zap:
  <...>
  scan_policy_from: /path/to/scan/policy
```
